Pythonweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.index, name='index'),

    # /music/id
    path('<int:album_id>/', views.detail, name='detail'),

    # /music/id/favorite
    path('<int:album_id>/favorite/', views.favorite, name='favorite'),
]

music/models.py
from django.db import models


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=500)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Album, Song


# Create your views here.
def index(request):
    all_albums = Album.objects.all()

    return render(request, 'music/index.html', {'all_albums': all_albums})


def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)

    return render(request, 'music/detail.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': "You did not select a valid song"
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album Detail</title>
</head>
<body>
<img src="{{ album.album_logo }}" width="200px" height="200px"/>
<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_meassage %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
    <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}"/>
    <label for="song{{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_favorite %}
        <img src="https://cdn4.iconfinder.com/data/icons/small-n-flat/24/star-128.png" width="18px" height="18px"/>
        {% endif %}
    </label><br>
    {% endfor %}
    <br>
    <input type="submit" value="Favorite">
</form>

</body>
</html>

music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Albums</title>
    <!-- Loads the path to static files -->
    {% load staticfiles %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">﻿
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <!-- Logo -->
        <div class="navbar-header">
            <a class=" navbar-brand" href="{% url 'music:index' %}">Krist</a>
        </div>
    </div>
</nav>
{% if all_albums %}
<h3>Here are all my Albums:</h3>
<ul>
    {% for album in all_albums %}
    <li>
        <a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a>
    </li>

    {% endfor %}
</ul>
{% else %}
<h3>You don't have any albums</h3>
{% endif %}
</body>
</html>